
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ae_project'
version: '1.0.0'
config-version: 2

# This setting configures for multiple use variables
# vars:
  # var1
  # var2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "docs"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "docs"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

seeds:
  +schema: ae_staging
  
models:
  staging:
    +schema: staging
    materialized: view
    +tags: ['staging']
  data_vault:
    +schema: data_vault
    materialized: table
    +tags: ['data_vault','tier1', 'raw', 'data_layer']
  dim_dwh:
    +schema: dim_dwh
    materialized: table
    +tags: ['dim_dwh','tier2', 'dwh', 'consumption']